
name: Merge

on:
  workflow_dispatch:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        run: |
          mkdir -p dist
          for theme in `ls -d src/* | sed 's/src\///'` ;do
            echo "concatenate $theme shortcodes and built-in ones"
            mkdir -p work/$theme
            cp src/built-in/*.js work/$theme/
            cp src/$theme/*.js   work/$theme/
            cat work/$theme/*.js > dist/zola-shortcodes-netlify-cms.$theme.js
          done
          rm -rf work
      - name: merge
        run: |
          git config --local user.email "hatappo@users.noreply.github.com"
          git config --local user.name "Fumihiko Hata"
          git add .
          git commit -m "Merge by themes" -a
          git push -f -q https://${{ secrets.GITHUB_TOKEN }}@github.com/hatappo/zola-shortcodes-netlify-cms.git main
