name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Make tarball
        run: |
          cd dist
          tar -zcvf zola-shortcodes-netlify-cms.tar.gz *.js
      - name: Release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zola-shortcodes-netlify-cms.tar.gz
          asset_name: "zola-shortcodes-netlify-cms-${{ steps.vars.outputs.tag }}.tar.gz"
          tag: ${{ github.ref }}
          body: "No defference between files on this release and ones in the 'dist' directory."
          overwrite: true
