on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zola-shortcodes-netlify-cms.js
          asset_name: "zola-shortcodes-netlify-cms-${GITHUB_REF/refs\/tags\//}.js"
          tag: ${{ github.ref }}
          body: "No defference between script on the release and raw one in the repository"
          overwrite: true
